Lectores/urls.py
from django.urls import path
from Lectores import views
from django.contrib.auth.views import LogoutView 

app_name = "lectores"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', LogoutView.as_view(template_name='lectores/login.html'), name='logout'),
    path('registro/', views.registrarse, name='registrarse')
]

    

inicio/urls.py
from django.urls import path
from inicio import views

app_name= 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('libros/crear/', views.crear_libro, name='crear_libro'),
    path('libros/', views.lista_libros, name='lista_libros'),
    path('usuario/agregar/', views.agregar_usuario, name='agregar_usuario'),
    path('usuario/', views.lista_usuarios, name='usuario'),
    path('libros/<int:pk>/', views.DetalleLibro.as_view(), name='detalle_libros'),
    path('libros/<int:pk>/modificar/', views.ModificarLibro.as_view(), name='modificar_libros'),
    path('libros/<int:pk>/eliminar/', views.EliminarLibro.as_view(), name='eliminar_libros'),
    
]

tp3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path ('', include ('inicio.urls')),
    path ('Lectores/', include ('Lectores.urls')),
    path('admin/', admin.site.urls),
]

Lectores/models.py
from django.db import models

# Create your models here.

inicio/models.py
from django.db import models

# Create your models here.

class Libro (models.Model):
    titulo = models.CharField(max_length=50)
    autor = models.CharField(max_length=20)
    año = models.IntegerField()
    editorial = models.CharField(max_length=20)
    
    def __str__(self):
        return f'TITULO: {self.titulo}  -  AUTOR: {self.autor}'
    
class Usuario (models.Model):
    nombre = models.CharField(max_length=50)
    direccion = models.CharField(max_length=20)
    dni = models.IntegerField()
    fecha_alta = models.DateField()
    
    def __str__(self):
        return f'NOMBRE: {self.nombre}  -  DNI: {self.dni}'

inicio/forms.py
from django import forms

class CrearLibroFormulario (forms.Form):
    titulo = forms.CharField(max_length=50)
    autor = forms.CharField(max_length=20)
    año = forms.IntegerField()
    editorial = forms.CharField(max_length=20)
    
class BuscarLibroFormulario (forms.Form):
    titulo = forms.CharField(max_length=50, required=False)
    
class AgregarUsuarioFormulario (forms.Form):
    nombre = forms.CharField(max_length=50)
    direccion = forms.CharField(max_length=20)
    dni = forms.IntegerField()
    fecha_alta = forms.DateField(required=False)
    
class BuscarUsuarioFormulario (forms.Form):
    nombre = forms.CharField(max_length=50, required=False)
    

Lectores/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate,login as django_login
from Lectores.form import MiFormularioDeCrecionDeUsurios

# Create your views here.
 
def login (request):
  
  if request.method == 'POST':
    formulario = AuthenticationForm(request, data=request.POST)
    if formulario.is_valid():
      usuario = formulario.cleaned_data['username']
      contrasenia = formulario.cleaned_data['password']
      
      user = authenticate(username=usuario, password=contrasenia)
      
      django_login(request, user)
      return redirect ('inicio:inicio')
      
    else:
        return render (request, 'lectores/login.html', {'formulario': formulario})
   
  formulario = AuthenticationForm()     
  return render (request, 'lectores/login.html', {'formulario': formulario})

def registrarse (request):
  
  if request.method == 'POST':
    formulario = MiFormularioDeCrecionDeUsurios (request.POST)
    if formulario.is_valid():
       formulario.save()
       return redirect ('lectores:login.html')
    else:
        return render (request, 'lectores/registro.html', {'formulario': formulario})

  formulario = MiFormularioDeCrecionDeUsurios()
  return render (request, 'lectores/registro.html', {'formulario': formulario})

inicio/views.py
from django.shortcuts import render, redirect
from inicio.forms import CrearLibroFormulario, BuscarLibroFormulario, BuscarUsuarioFormulario, AgregarUsuarioFormulario
from inicio.models import Libro, Usuario
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

def inicio(request):
    return render(request,'inicio/inicio.html')

@login_required
def crear_libro(request):
    
    if request.method == 'POST':
        formulario = CrearLibroFormulario(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            libro = Libro(titulo=informacion['titulo'],autor=informacion['autor'],año=informacion['año'],editorial=informacion['editorial'], cargado= request.user)
            libro.save()
            return redirect('inicio:lista_libros')
        else:
            return render(request,'inicio/crear_libro.html', {'formulario': formulario})
    
    formulario = CrearLibroFormulario()
    return render(request,'inicio/crear_libro.html', {'formulario': formulario})

def lista_libros(request):
    formulario = BuscarLibroFormulario(request.GET)
    if formulario.is_valid():
            titulo_buscar = formulario.cleaned_data.get('titulo', '')
            listado_libros = Libro.objects.filter(titulo__icontains=titulo_buscar)
    formulario = BuscarLibroFormulario()
    return render(request,'inicio/lista_libros.html', {'formulario': formulario, 'Libros': listado_libros})

def agregar_usuario(request):
    
    if request.method == 'POST':
        formulario = AgregarUsuarioFormulario(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            usuario = Usuario(nombre=informacion['nombre'],direccion=informacion['direccion'],dni=informacion['dni'],fecha_alta=informacion['fecha_alta'])
            usuario.save()
            return redirect('inicio:usuario')
        else:
            return render(request,'inicio/agregar_usuario.html', {'formulario': formulario})
    
    formulario = AgregarUsuarioFormulario()
    return render(request,'inicio/agregar_usuario.html', {'formulario': formulario})

def lista_usuarios(request):
    formulario = BuscarUsuarioFormulario(request.GET)
    if formulario.is_valid():
            nombre_buscar = formulario.cleaned_data.get('nombre','')
            listado_usuarios = Usuario.objects.filter(nombre__icontains=nombre_buscar)
    formulario = BuscarUsuarioFormulario()
    return render(request,'inicio/usuario.html', {'formulario': formulario, 'Usuario': listado_usuarios})


class DetalleLibro(DetailView):
    model = Libro
    template_name = "inicio/detalle_libros.html"
    
    
class ModificarLibro(UpdateView,LoginRequiredMixin):
    model = Libro
    fields= ['titulo', 'autor', 'año', 'editorial']
    template_name = "inicio/modificar_libros.html"
    success_url = reverse_lazy('inicio:lista_libros')
    
class EliminarLibro(DeleteView,LoginRequiredMixin):
    model = Libro
    template_name = "inicio/eliminar_libros.html"
    success_url = reverse_lazy('inicio:lista_libros')
    

Lectores/templates/lectores/login.html
{%  extends 'base.html' %}

{%block title_head %}
<title>Login</title>
{% endblock title_head %}

{%block h1_header %}
Login
{% endblock h1_header %}

{%block contenido %}
<form action= {% url 'lectores:login' %} method="POST"> 
  {% csrf_token %} 
    <table>
      {{formulario}}
    </table>
    <button>Login</button> 
</form>
{% endblock contenido %}

Lectores/templates/lectores/logout.html
{%  extends 'base.html' %}

{%block title_head %}
<title>Logout</title>
{% endblock title_head %}

{%block h1_header %}
Ha sido deslogeado
{% endblock h1_header %}

{%block contenido %}
{% endblock contenido %}

Lectores/templates/lectores/registro.html
{%  extends 'base.html' %}

{%block title_head %}
<title>Registrarse</title>
{% endblock title_head %}

{%block h1_header %}
Registro
{% endblock h1_header %}

{%block contenido %}
<form action= {% url 'lectores:registrarse' %} method="POST"> 
    {% csrf_token %}
    <table>
      {{formulario}}
    </table>
    <button>Registrar</button> 
</form>
{% endblock contenido %}

inicio/templates/inicio/agregar_usuario.html
{%  extends 'base.html' %}

{%block title_head %}
<title>Crear Usuario</title>
{% endblock title_head %}

{%block h1_header %}
Agregar Usuario
{% endblock h1_header %}

{%block contenido %}

<p>{{mensaje}}</p>

<form action="" method= "post">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Crear</button>
</form>

{% endblock contenido %}

inicio/templates/inicio/crear_libro.html
{%  extends 'base.html' %}

{%block title_head %}
<title>Crear Libro</title>
{% endblock title_head %}

{%block h1_header %}
Creando Libros
{% endblock h1_header %}

{%block contenido %}

<p>{{mensaje}}</p>

<form action="" method= "post">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Crear</button>
</form>

{% endblock contenido %}

inicio/templates/inicio/detalle_libros.html
{%  extends 'base.html' %}

{%block title_head %}
<title>Libro</title>
{% endblock title_head %}

{%block h1_header %}
Detalles del libro{{Libro.titulo}}
{% endblock h1_header %}

{%block contenido %}
<li>Autor: {{Libro.autor}} </li>
<li>Año: {{Libro.año}} </li>
<li>Editorial: {{Libro.editorial}} </li>
<li>Cargado Por: {{Libro.cargo}} </li>
{% endblock contenido %}

inicio/templates/inicio/eliminar_libros.html
{%  extends 'base.html' %}

{%block title_head %}
<title>Eliminar Libro</title>
{% endblock title_head %}

{%block h1_header %}
Eliminando Libro {{Libro.titulo}}
{% endblock h1_header %}

{%block contenido %}


<form method= "post">
    {% csrf_token %}
    <p> Esta por eliminar el libro:  {{Libro}}</p>
    <button>Confirmar</button>
</form>

{% endblock contenido %}

inicio/templates/inicio/inicio.html
{%  extends 'base.html' %}

{%block title_head %}
<title>Inicio</title>
{% endblock title_head %}

{%block h1_header %}
Gestion de Biblioteca
{% endblock h1_header %}

{%block contenido %}
<p>
    *pagina en desarrollo*
</p>
{% endblock contenido %}

inicio/templates/inicio/lista_libros.html
{%  extends 'base.html' %}

{%block title_head %}
<title>Libros</title>
{% endblock title_head %}

{%block h1_header %}
Listado de Libros
{% endblock h1_header %}

{%block contenido %}
<button>
    <a class="navbar-brand" href={% url 'inicio:crear_libro' %}>Agrear Libro</a>
</button>

{% comment %} <form action= "" method="get">
    {{formulario}}
    <button>Buscar</button> 
</form> {% endcomment %}

<form action={% url 'inicio:lista_libros' %}>
    <table>
      {{formulario}}
    </table>
    <button>Buscar</button> 
</form>

{%if Libros%} 
{%for Libro in Libros%}
{% comment %} <li>Titulo: {{Libro.titulo}} - Autor: {{Libro.autor}} - Editorial: {{Libro.editorial}}</li> {% endcomment %}
<li>
    {% comment %} {{Libro}} {% endcomment %}
    <a class="navbar-brand" href={% url 'inicio:detalle_libros' Libro.id %}>{{Libro}}</a>
    <button>
    <a class="navbar-brand" href={% url 'inicio:modificar_libros' Libro.id %}>Modificar</a>
    </button> 
    <button>
    <a class="navbar-brand" href={% url 'inicio:eliminar_libros' Libro.id %}>Eliminar</a>
    </button> 
</li>
{% endfor %}
{%else%}
<p>No Hay Datos Que Coincidan Con La Busqueda</p> 
{% endif %} 
{% endblock contenido %}

inicio/templates/inicio/modificar_libros.html
{%  extends 'base.html' %}

{%block title_head %}
<title>Modificar Libro</title>
{% endblock title_head %}

{%block h1_header %}
Modificando Libro {{Libro.titulo}}
{% endblock h1_header %}

{%block contenido %}
<form method= "post">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Modificar</button>
</form>

{% endblock contenido %}

inicio/templates/inicio/usuario.html
{%  extends 'base.html' %}

{%block title_head %}
<title>Lectores</title>
{% endblock title_head %}

{%block h1_header %}
Lectores
{% endblock h1_header %}

{%block contenido %}
<button>
    <a class="navbar-brand" href={% url 'inicio:agregar_usuario' %}>Agrear Lector</a>
</button>
{% comment %} <form action= "" method="get">
    {{formulario}}
    <button>Buscar</button> 
</form> {% endcomment %}


<form action={% url 'inicio:usuario' %}>
    <table>
      {{formulario}}
    </table>
    <button>Buscar</button> 
</form>

{%if Usuario%} 
{%for Usuario in Usuario%}
{% comment %} <li>NOMBRE:{{Usuario.nombre}} - DIRECCION:{{Usuario.direccion}} - FECHA DE ALTA:{{Usuario.fecha_alta}}</li> {% endcomment %}
<li>
    {{Usuario}}
</li>
{% endfor %}
{%else%}
<p>No Hay Datos Que Coincidan Con La Busqueda</p> 
{% endif %} 
{% endblock contenido %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Landing Page - Start Bootstrap Theme</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
                <a class="navbar-brand" href={% url 'inicio:lista_libros' %}>Libros</a>
                <a class="navbar-brand" href={% url 'inicio:usuario' %}>Lectores</a>
                {% if request.user.is_authenticated %}
                <a class="btn btn-primary" href={% url 'lectores:logout' %}>Logout</a>
                {% else %}
                <a class="btn btn-secondary" href={% url 'lectores:login' %}>Login</a>
                <a class="btn btn-secondary" href={% url 'lectores:registrarse' %}>Registrarse</a>
                {% endif %}
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">
                                {% block h1_header %}
                                {% endblock h1_header %}    
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% block contenido %}
        {% endblock contenido %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Intento de Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static 'js/scripts.js' %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>